name: build-test

on: [push, pull_request]

jobs:

  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    
    - name: Get latest go version
      id: get-semantic-version
      run: echo "::set-output name=SEMANTIC_VERSION::$(curl https://golang.org/VERSION?m=text | cut -c 3-)"
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{steps.get-semantic-version.outputs.SEMANTIC_VERSION}}

    - name: Build
      run: go build -v ./...
      
    - name: Test and run coverage
      run: go test -v ./... -coverprofile=coverage.out -covermode=atomic # -race flag removed here because some tests use more than 8128 go routines.
    
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
