name: Lint Code Base

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: {}

#For private repositories, it should be this.
#permissions:
  #contents: read

jobs:
  lint:
    name: Lint code base
    uses: andrew-field/reusable-workflows/.github/workflows/linter.yml@master
